### ISSUE TITLE
Using conditionals within a section and avoiding new lines for absent entry

### ISSUE THREAD

**Issue by demacdo** [mrzool/cv-boilerplate#14]
Hi, great repo. I'm looking for some help editing the template.tex file, I'm very likely doing something wrong but I can't seem to get the formatting that I want. 

I want to have optional items within a category. See below: I'd like to differentiate between an undergrad degree project and a graduate thesis. But when I make the pdf, if a category doesn't have a given entry (here, either "thesis" or "capstone"), it still produces a new line.

I've tried moving around or removing the `\\` items, but can't get it to work.

Any advice on getting consistent formatting? Thanks!

```
education:
- year: 2018--Present
  subject: Engineering
  degree: PhD
  institute: University of Somewhere
  department: Department of Engineering
  city: City
  thesis: Study of something.
  supervisor: Prof Jack

- year: 2016--2018
  subject: Engineering
  degree: MSc
  institute: University of Somewhere Else
  department: Department of Engineering
  city: Town
  thesis: Research about topic.
  supervisor: Prof Jill

- year: 2011--2015
  subject: Engineering
  minor: Art
  degree: BASc
  institute: University of Nowhere
  department: Department of Engineering
  city: Nowhere.
  capstone: Undergrad project title.
  supervisor: Prof Bob

```

```
$if(education)$
\section*{Education}
\noindent
$for(education)$
\note{$education.year$}\textbf{$education.subject$}$if(education.degree)$, $education.degree$\\$endif$
$education.department$, \emph{$education.institute$}\\
$if(education.thesis)$Thesis: $education.thesis$\\$endif$
$if(education.capstone)$Capstone project: $education.capstone$\\$endif$
$if(education.supervisor)$Supervisor: $education.supervisor$$endif$\\[.2cm]
```
![Screen Shot 2022-01-19 at 2 39 16 PM](https://user-images.githubusercontent.com/26281358/150201870-33182003-b491-42df-a900-c0f130989b7a.png)
